using System;

namespace EmbeddedMonoInjector;

[Flags]
public enum ProcessAccessRights : uint
{
	PROCESS_ALL_ACCESS = 0x1FFFFFu,
	PROCESS_CREATE_PROCESS = 0x80u,
	PROCESS_CREATE_THREAD = 2u,
	PROCESS_DUP_HANDLE = 0x40u,
	PROCESS_QUERY_INFORMATION = 0x400u,
	PROCESS_QUERY_LIMITED_INFORMATION = 0x1000u,
	PROCESS_SET_INFORMATION = 0x200u,
	PROCESS_SET_QUOTA = 0x100u,
	PROCESS_SUSPEND_RESUME = 0x800u,
	PROCESS_TERMINATE = 1u,
	PROCESS_VM_OPERATION = 8u,
	PROCESS_VM_READ = 0x10u,
	PROCESS_VM_WRITE = 0x20u,
	SYNCHRONIZE = 0x100000u
}

